DROP TABLE "EDS"."HIGH_LEVEL_LAND" purge;
DROP TABLE "EDS"."ACCESS_CLASS" purge;
DROP TABLE "EDS"."APPLICATION_SUPPLEMENT" purge;
DROP TABLE "EDS"."APP_SUPP_DATA" purge;
DROP sequence "EDS"."HLL_SEQ";
DROP SEQUENCE "EDS"."APP_SUPP_SEQ" ;
DROP SEQUENCE "EDS"."ACCESS_CLASS_SEQ" ;
DROP SEQUENCE "EDS"."ASD_SEQ" ;
CREATE SEQUENCE "EDS"."HLL_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "EDS"."APP_SUPP_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "EDS"."ACCESS_CLASS_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "EDS"."ASD_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
  GRANT
  SELECT ON "EDS"."HLL_SEQ" TO eds_wls;
  GRANT
  SELECT ON "EDS"."APP_SUPP_SEQ" TO eds_wls;
  GRANT
  SELECT ON "EDS"."ACCESS_CLASS_SEQ" TO eds_wls;
  GRANT
  SELECT ON "EDS"."ASD_SEQ" TO EDS_WLS;
  CREATE TABLE "EDS"."APP_SUPP_DATA"
    (
      "ASD_ID"               NUMBER(12,0) NOT NULL ENABLE,
      "STRING_VALUE"         VARCHAR2(300 BYTE) ,
      "BOOLEAN_VALUE"        VARCHAR2(1 BYTE) ,
      "DOMAIN_CODE_ID_VALUE" NUMBER(12,0) ,
      "TIMESTAMP_VALUE"      DATE ,
      "LABEL"                VARCHAR2(300 BYTE) ,
      "OTHERS"                VARCHAR2(300 BYTE) ,
      "CREATE_USERID"        VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP"     DATE NOT NULL ENABLE,
      "UPDATE_USERID"        VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP"     DATE,
      CONSTRAINT "APP_SUPP_DATA_PK" PRIMARY KEY ("ASD_ID") USING INDEX ENABLE
    ) ;
  CREATE TABLE "EDS"."APPLICATION_SUPPLEMENT"
    (
      "APP_SUPP_ID"      NUMBER(12,0) NOT NULL ENABLE,
      "ACTIVITY_TYPE"    VARCHAR2(20 BYTE) NOT NULL ENABLE,
      "FORM_NAME"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
      "FORM_DATE"        DATE NOT NULL ENABLE,
      "CREATE_USERID"    VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP" DATE NOT NULL ENABLE,
      "UPDATE_USERID"    VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP" DATE,
      CONSTRAINT "APPLICATION_SUPPLEMENT_PK" PRIMARY KEY ("APP_SUPP_ID") USING INDEX ENABLE
    ) ;
  CREATE TABLE "EDS"."ACCESS_CLASS"
    (
      "ACCESS_CLASS_ID"     NUMBER(12,0)NOT NULL ENABLE,
      "APP_SUPP_ID"      NUMBER(12,0) NOT NULL ENABLE,
      "ASD_ID_ROAD_CLASS"   NUMBER(12,0),
      "ASD_ID_VAR_CON_TECH" NUMBER(12,0),
      "CREATE_USERID"       VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP"    DATE NOT NULL ENABLE,
      "UPDATE_USERID"       VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP"    DATE ,
      CONSTRAINT "ACCESS_CLASS_PK" PRIMARY KEY ("ACCESS_CLASS_ID") USING INDEX ENABLE,
      CONSTRAINT "APP_SUPP_ID_FK" FOREIGN KEY ("APP_SUPP_ID") REFERENCES "EDS"."APPLICATION_SUPPLEMENT" ("APP_SUPP_ID") ENABLE,
      CONSTRAINT "ASD_ID_ROAD_CLASS_FK1" FOREIGN KEY ("ASD_ID_ROAD_CLASS") REFERENCES "EDS"."APP_SUPP_DATA" ("ASD_ID") ENABLE,
      CONSTRAINT "ASD_ID_ROAD_CLASS_FK2" FOREIGN KEY ("ASD_ID_VAR_CON_TECH") REFERENCES "EDS"."APP_SUPP_DATA" ("ASD_ID") ENABLE
    ) ;
  CREATE TABLE "EDS"."HIGH_LEVEL_LAND"
    (
      "HLL_ID"                      NUMBER(12,0) NOT NULL ENABLE,
      "ACCESS_CLASS_ID"             NUMBER(12,0),
      "ASD_ID_NAME"                 NUMBER(12,0),
      "ASD_ID_DIRECTION"            NUMBER(12,0),
      "ASD_ID_CONTRACT_SIGNED_DATE" NUMBER(12,0),
      "CREATE_USERID"               VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP"            DATE NOT NULL ENABLE,
      "UPDATE_USERID"               VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP"            DATE ,
      CONSTRAINT "HIGH_LEVEL_LAND_PK" PRIMARY KEY ("HLL_ID") USING INDEX ENABLE,
      CONSTRAINT "HIGH_LEVEL_LAND_ACC_CLS_FK1" FOREIGN KEY ("ACCESS_CLASS_ID") REFERENCES "EDS"."ACCESS_CLASS" ("ACCESS_CLASS_ID") ENABLE,
      CONSTRAINT "HIGH_LEVEL_LAND_FK1" FOREIGN KEY ("ASD_ID_NAME") REFERENCES "EDS"."APP_SUPP_DATA" ("ASD_ID") ENABLE,
      CONSTRAINT "HIGH_LEVEL_LAND_FK2" FOREIGN KEY ("ASD_ID_DIRECTION") REFERENCES "EDS"."APP_SUPP_DATA" ("ASD_ID") ENABLE,
      CONSTRAINT "HIGH_LEVEL_LAND_FK3" FOREIGN KEY ("ASD_ID_CONTRACT_SIGNED_DATE") REFERENCES "EDS"."APP_SUPP_DATA" ("ASD_ID") ENABLE
    ) ;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT ON EDS.ACCESS_CLASS TO EDS_WLS;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT ON EDS.APP_SUPP_DATA TO EDS_WLS;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT ON EDS.HIGH_LEVEL_LAND TO EDS_WLS;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT ON EDS.APPLICATION_SUPPLEMENT TO EDS_WLS;
