DROP
  TABLE "CHIEF_DOM"."DOMAIN_NAMES" PURGE;
DROP
  TABLE "CHIEF_DOM"."DOMAIN_CODES" purge;
CREATE
  TABLE "CHIEF_DOM"."DOMAIN_NAMES"
  (
    DOMAIN_NAME_ID   NUMBER(22,0),
    DOMAIN_NAME      VARCHAR2(30),
    APP_CODE         VARCHAR2(30),
    DOMAIN_PROMPT    VARCHAR2(30),
    DESCRIPTION      VARCHAR2(30),
    ROLE             VARCHAR2(30),
    CREATE_USERID    VARCHAR2(30) NOT NULL,
    CREATE_TIMESTAMP TIMESTAMP NOT NULL,
    UPDATE_USERID    VARCHAR2(30),
    UPDATE_TIMESTAMP TIMESTAMP
  ) ;
CREATE
  TABLE "CHIEF_DOM"."DOMAIN_CODES"
  (
    DOMAIN_CODE_ID   NUMBER(22,0),
    CODE             VARCHAR2(30),
    DESCRIPTION      VARCHAR2(30),
    DOMAIN_PROMPT    VARCHAR2(30),
    EFFECTIVE_DATE   TIMESTAMP,
    TERMINATION_DATE TIMESTAMP,
    DOMAIN_NAME_ID   NUMBER(22,0),
    CREATE_USERID    VARCHAR2(30) NOT NULL,
    CREATE_TIMESTAMP TIMESTAMP NOT NULL,
    UPDATE_USERID    VARCHAR2(30),
    UPDATE_TIMESTAMP TIMESTAMP
  ) ;
GRANT
UPDATE,
SELECT,
INSERT,
DELETE
  ON CHIEF_DOM.DOMAIN_NAMES TO EDS_WLS;
GRANT
UPDATE,
SELECT,
INSERT,
DELETE
  ON CHIEF_DOM.DOMAIN_CODES TO EDS_WLS; 