DROP
  TABLE "EDS"."APP_SUPP_DATA" purge;

DROP
  TABLE "EDS"."HIGH_LEVEL_PLAN_DATA" purge;
DROP
  TABLE "EDS"."HIGH_LEVEL_PLAN" purge;
 
DROP
  TABLE "EDS"."APPLICATION_SUPPLEMENT" purge;

DROP
  TABLE "EDS"."DATA_ITEM" purge;

DROP
  sequence "EDS"."HLP_SEQ";
DROP
  SEQUENCE "EDS"."APP_SUPP_SEQ" ;
DROP
  SEQUENCE "EDS"."ACCESS_CLASS_SEQ" ;
DROP
  SEQUENCE "EDS"."DATA_ITEM_SEQ" ;

CREATE SEQUENCE "EDS"."HLP_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1
  START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "EDS"."APP_SUPP_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT
  BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "EDS"."ACCESS_CLASS_SEQ" MINVALUE 1 MAXVALUE 99999999999
  INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "EDS"."DATA_ITEM_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1
  START WITH 1 CACHE 20 NOORDER NOCYCLE ;
  GRANT
  SELECT
    ON "EDS"."HLP_SEQ" TO eds_wls;
  GRANT
  SELECT
    ON "EDS"."APP_SUPP_SEQ" TO eds_wls;
   
     GRANT
  SELECT
    ON "EDS"."DATA_ITEM_SEQ" TO EDS_WLS;
  CREATE
    TABLE "EDS"."DATA_ITEM"
    (
      "DATA_ITEM_ID"               NUMBER(12,0) NOT NULL ENABLE,
      "DOMAIN_CODE_ID_FIELD" NUMBER(12,0) NOT NULL ENABLE,      
      "STRING_VALUE"         VARCHAR2(300 BYTE) ,
      "BOOLEAN_VALUE"        VARCHAR2(1 BYTE) ,
      "DOMAIN_CODE_ID_VALUE" NUMBER(12,0) ,
      "TIMESTAMP_VALUE"      DATE ,
      "LABEL"                VARCHAR2(300 BYTE) ,
      "OTHERS"               VARCHAR2(300 BYTE) ,
      "CREATE_USERID"        VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP"     DATE NOT NULL ENABLE,
      "UPDATE_USERID"        VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP"     DATE,
      CONSTRAINT "DATA_ITEM_PK" PRIMARY KEY ("DATA_ITEM_ID") USING INDEX ENABLE
    ) ;
  CREATE
    TABLE "EDS"."APPLICATION_SUPPLEMENT"
    (
      "APP_SUPP_ID"      NUMBER(12,0) NOT NULL ENABLE,
      "ACTIVITY_TYPE"    VARCHAR2(20 BYTE) NOT NULL ENABLE,
      "FORM_NAME"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
      "FORM_DATE"        DATE NOT NULL ENABLE,
      "CREATE_USERID"    VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP" DATE NOT NULL ENABLE,
      "UPDATE_USERID"    VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP" DATE,
      CONSTRAINT "APPLICATION_SUPPLEMENT_PK" PRIMARY KEY ("APP_SUPP_ID") USING
      INDEX ENABLE
    ) ;
   
     CREATE
    TABLE "EDS"."HIGH_LEVEL_PLAN"
    (
      "HLP_ID"                      NUMBER(12,0) NOT NULL ENABLE,
      "APP_SUPP_ID"             NUMBER(12,0),
       "CREATE_USERID"               VARCHAR2(30 BYTE) NOT NULL ENABLE,
      "CREATE_TIMESTAMP"            DATE NOT NULL ENABLE,
      "UPDATE_USERID"               VARCHAR2(30 BYTE),
      "UPDATE_TIMESTAMP"            DATE ,
      CONSTRAINT "HIGH_LEVEL_PLAN_PK" PRIMARY KEY ("HLP_ID") USING INDEX ENABLE
      ,
      CONSTRAINT "HIGH_LEVEL_PLAN_ACC_CLS_FK1" FOREIGN KEY ("APP_SUPP_ID")
      REFERENCES "EDS"."APPLICATION_SUPPLEMENT" ("APP_SUPP_ID") ENABLE
        ) ;
  CREATE
    TABLE "EDS"."HIGH_LEVEL_PLAN_DATA"
    (
      "HLP_ID" NUMBER(12,0) NOT NULL ENABLE,
      "DATA_ITEM_ID" NUMBER(12,0) NOT NULL ENABLE,
      "LABEL"  VARCHAR2(100) NOT NULL ENABLE,
      CONSTRAINT "HIGH_LEVEL_PLAN_DATA_PK" PRIMARY KEY ("HLP_ID","DATA_ITEM_ID")
      USING INDEX ENABLE,
      CONSTRAINT "HIGH_LEVEL_PLAN_DATA_FK1" FOREIGN KEY ("HLP_ID") REFERENCES
      "EDS"."HIGH_LEVEL_PLAN" ("HLP_ID") ENABLE,
      CONSTRAINT "HIGH_LEVEL_PLAN_DATA_FK2" FOREIGN KEY ("DATA_ITEM_ID") REFERENCES
      "EDS"."DATA_ITEM" ("DATA_ITEM_ID") ENABLE
    ) ;
    
      CREATE
    TABLE "EDS"."APP_SUPP_DATA"
    (
      "APP_SUPP_ID" NUMBER(12,0) NOT NULL ENABLE,
      "DATA_ITEM_ID" NUMBER(12,0) NOT NULL ENABLE,
      "LABEL"  VARCHAR2(100) NOT NULL ENABLE,
      CONSTRAINT "APP_SUPP_DATA_PK" PRIMARY KEY ("APP_SUPP_ID","DATA_ITEM_ID")
      USING INDEX ENABLE,
      CONSTRAINT "APP_SUPP_DATA_FK1" FOREIGN KEY ("APP_SUPP_ID") REFERENCES
      "EDS"."APPLICATION_SUPPLEMENT" ("APP_SUPP_ID") ENABLE,
      CONSTRAINT "APP_SUPP_DATA_FK2" FOREIGN KEY ("DATA_ITEM_ID") REFERENCES
      "EDS"."DATA_ITEM" ("DATA_ITEM_ID") ENABLE
    ) ;
    
  GRANT
  UPDATE ,
  INSERT ,
  SELECT
    ON EDS.APP_SUPP_DATA TO EDS_WLS;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT
    ON EDS.DATA_ITEM TO EDS_WLS;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT
    ON EDS.HIGH_LEVEL_PLAN TO EDS_WLS;
  GRANT
  UPDATE ,
  INSERT ,
  SELECT
    ON EDS.APPLICATION_SUPPLEMENT TO EDS_WLS;
  GRANT
  UPDATE ,
  DELETE,
  INSERT ,
  SELECT
    ON EDS.HIGH_LEVEL_PLAN_DATA TO EDS_WLS;
