package appsupp.module;

// Generated Aug 19, 2010 5:16:14 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DomainName generated by hbm2java
 */
@Entity
@Table(name = "DOMAIN_NAME", schema = "CHIEF_DOM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DOMAIN_NAME", "APP_CODE" }))
public class DomainName implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -824440902226301775L;
	private BigDecimal domainNameId;
	private String domainName;
	private String appCode;
	private String domainPrompt;
	private String description;
	private String role;
	private String createUserid;
	private Timestamp createTimestamp;
	private String updateUserid;
	private Timestamp updateTimestamp;
	private List<DomainCode> domainCodes = new ArrayList<DomainCode>(0);

	public DomainName() {
	}

	public DomainName(BigDecimal domainNameId, String domainName,
			String createUserid, Timestamp createTimestamp) {
		this.domainNameId = domainNameId;
		this.domainName = domainName;
		this.createUserid = createUserid;
		this.createTimestamp = createTimestamp;
	}

	public DomainName(BigDecimal domainNameId, String domainName,
			String appCode, String domainPrompt, String description,
			String role, String createUserid, Timestamp createTimestamp,
			String updateUserid, Timestamp updateTimestamp,
			List<DomainCode> domainCodes) {
		this.domainNameId = domainNameId;
		this.domainName = domainName;
		this.appCode = appCode;
		this.domainPrompt = domainPrompt;
		this.description = description;
		this.role = role;
		this.createUserid = createUserid;
		this.createTimestamp = createTimestamp;
		this.updateUserid = updateUserid;
		this.updateTimestamp = updateTimestamp;
		this.domainCodes = domainCodes;
	}

	@Id
	@Column(name = "DOMAIN_NAME_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDomainNameId() {
		return this.domainNameId;
	}

	public void setDomainNameId(BigDecimal domainNameId) {
		this.domainNameId = domainNameId;
	}

	@Column(name = "DOMAIN_NAME", nullable = false, length = 10)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "APP_CODE", length = 10)
	public String getAppCode() {
		return this.appCode;
	}

	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	@Column(name = "DOMAIN_PROMPT")
	public String getDomainPrompt() {
		return this.domainPrompt;
	}

	public void setDomainPrompt(String domainPrompt) {
		this.domainPrompt = domainPrompt;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ROLE", length = 30)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "CREATE_USERID", nullable = false, length = 30)
	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIMESTAMP", nullable = false, length = 7)
	public Timestamp getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Timestamp createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Column(name = "UPDATE_USERID", length = 30)
	public String getUpdateUserid() {
		return this.updateUserid;
	}

	public void setUpdateUserid(String updateUserid) {
		this.updateUserid = updateUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIMESTAMP", length = 7)
	public Timestamp getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Timestamp updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "domainName")
	public List<DomainCode> getDomainCodes() {
		return this.domainCodes;
	}

	public void setDomainCodes(List<DomainCode> domainCodes) {
		this.domainCodes = domainCodes;
	}

}
